name: Deploy QA release

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Branch to build APK from'
        required: true
  push: 
    branches: 
      - 'test'
    
jobs:
  build-and-deploy: 
    runs-on: ubuntu-latest
     
    steps:
      - name: CheckOut repository ⚓
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.target_branch }}

      - name: Grant execution permissions to gradlew 🤖
        run: cd SuperTool && chmod +x ./gradlew
    
      - name: Set up JDK 17 🚥
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Verify Java version 👀
        run: java -version

      - name: Create google-services.json 🤖
        run: |
          cat <<EOF > $GITHUB_WORKSPACE/SuperTool/app/google-services.json
          ${{ secrets.GOOGLE_SERVICES_JSON }}
          EOF

      - name: Set up secrets 😶
        run: |
          cat <<EOF > $GITHUB_WORKSPACE/SuperTool/local.properties
          WEB_ID=${{ secrets.WEB_ID }}
          EOF

      - name: Build the code 🚀
        run: cd SuperTool && ./gradlew build

      - name: Keystore decode 🤖
        run: echo "${{ secrets.KEYSTORE_B64 }}" | base64 --decode > keystore.jks

      - name: Build unsigned APK 🤖🚥
        run: |
          cd SuperTool && ./gradlew assembleRelease
        
      - name: Signing APK 🖋️
        run: |
          jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 \
          -keystore keystore.jks \
          -storepass ${{ secrets.KEYSTORE_PASSWORD }} \
          -keypass ${{ secrets.KEY_PASSWORD }} \
          app/build/outputs/apk/release/app-release-unsigned.apk ${{ secrets.KEY_ALIAS }}

      - name: upload artifact to Firebase App Distribution 🤖🚀
        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_CREDENTIAL_FILE_CONTENT }}
          groups: Testers
          file: SuperTool/app/build/outputs/apk/release/app-release-unsigned.apk
