name: Deploy QA release

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Branch to build APK from'
        required: true
  push: 
    branches: 
      - 'test'
    
jobs:
  build-and-deploy: 
    runs-on: ubuntu-latest
     
    steps:
      - name: CheckOut repository ⚓
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.target_branch }}

      - name: Grant execution permissions to gradlew 🤖
        run: cd SuperTool && chmod +x ./gradlew
    
      - name: Set up JDK 17 🚥
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Verify Java version 👀
        run: java -version

      - name: Create google-services.json 🤖
        run: |
          echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > $GITHUB_WORKSPACE/SuperTool/app/google-services.json
          cat $GITHUB_WORKSPACE/SuperTool/app/google-services.json

      - name: Build the code 🚀
        run: cd SuperTool && ./gradlew build

      - name: Install Firebase CLI 🤖🚥
        run: |
          curl -sL https://firebase.tools | bash

      - name: Build APK 🤖🚥
        run: |
          cd SuperTool && ./gradlew assembleRelease

      - name: Upload APK to Firebase 🤖🚀
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_APP_DISTRIBUTION_TOKEN }}
        run: |
          firebase appdistribution:distribute \
          SuperTool/app/build/outputs/apk/release/app-release-unsigned.apk \
          --app ${{ secrets.FIREBASE_APP_ID }}