name: Deploy QA release

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Branch to build APK from'
        required: true
  push: 
    branches: 
      - 'test'
    
jobs:
  build-and-deploy: 
    runs-on: ubuntu-latest
     
    steps:
      - name: CheckOut repository ⚓
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.target_branch }}

      - name: Grant execution permissions to gradlew 🤖
        run: cd SuperTool && chmod +x ./gradlew
    
      - name: Set up JDK 17 🚥
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Verify Java version 👀
        run: java -version

      - name: Create google-services.json 🤖
        run: |
          echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > $GITHUB_WORKSPACE/SuperTool/app/google-services.json
          cat $GITHUB_WORKSPACE/SuperTool/app/google-services.json

      - name: Build the code 🚀
        run: cd SuperTool && ./gradlew build

      - name: Build unsigned APK 🤖🚥
        run: |
          cd SuperTool && ./gradlew assembleDebug

      - name: upload artifact to Firebase App Distribution 🤖🚀
        uses: wzieba/Firebase-Distribution-Github-Action@v1.5.1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}   
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_CREDENTIAL_FILE_CONTENT }}      
          groups: testers
          file: SuperTool/app/build/outputs/apk/debug/app-debug.apk